# 1. Build Stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY ./invoice-parsing/package*.json ./

RUN npm ci

COPY ./invoice-parsing .

RUN npm run build

# 2. Runtime Stage
FROM node:20-alpine AS runner

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000

RUN addgroup -g 1001 nodejs \
    && adduser -S -u 1001 nextjs -G nodejs

WORKDIR /app

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.mjs ./next.config.mjs

RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

CMD ["npm", "run", "start"]
